/* Radar.js v20.22. Copyright 2017 Cedexis. All rights reserved. */
if(!cedexis||!cedexis.start){if(!cedexis)var cedexis={};(function(_){_.MP="//radar.cedexis.com/releases/1486141954/";
_.MI={"radar":[],"impact":["radar"],"video":["radar"]};_.MU={"radar":["radar.js"],"impact":["impact.js"],"video":["video.js"]};
var ba,t,ca,w,fa,ga,ha,ia,ja,ka,la,ma,na,C,oa,pa,ra,sa,D,ya,za,Aa,Ba,Fa,Ea,Ga,Ja,Ka,Ma,Oa,Pa,Qa,Ra,Wa,ab,bb,Xa,eb,db,Za,Ua,Sa,mb,nb,pb,sb,tb,vb,ub,wb,xb,yb,Ab,Bb,Cb,Db,Fb,Jb,Nb,Pb,Sb,Tb,Ub,Rb,Wb,Xb,Zb,L,ac,cc,ec,fc,hc,jc,kc,lc,ic,O,K,dc,gc,mc,M,$b,nc,oc,sc,qc,tc,rc,uc,xc,wc,yc,vc,ob,Bc,Cc,Ac,Fc,P,Jc,Ic,Kc,rb,Mc,Nc,r;_.q=function(a){return void 0!==a};ba=function(a,b){for(var c=a.split("."),d=b||r,e;e=c.shift();)if(null!=d[e])d=d[e];else return null;return d};t=function(){};
ca=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.da=function(a){return"array"==ca(a)};_.u=function(a){return"string"==typeof a};_.v=function(a){return"number"==typeof a};w=function(a){return"function"==ca(a)};_.ea=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};fa=function(a,b,c){return a.call.apply(a.bind,arguments)};
ga=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};_.x=function(a,b,c){_.x=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?fa:ga;return _.x.apply(null,arguments)};
_.y=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};_.z=function(){return+new Date};ha=function(a,b){var c=a.split("."),d=r;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&_.q(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}};
ia=function(a,b){function c(){}c.prototype=b.prototype;a.Ca=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Da=function(a,c,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[c].apply(a,g)}};ja=function(a,b){return a<b?-1:a>b?1:0};_.A=function(a,b,c){for(var d=a.length,e=_.u(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
ka=function(a){for(var b="chrome/43;opera mini;skyfire;teashark;uzard;puffin;yandex;dynatrace".split(";"),c=b.length,d=_.u(b)?b.split(""):b,e=0;e<c;e++)if(e in d&&a.call(void 0,d[e],e,b))return!0;return!1};la=function(a,b){for(var c=a.length,d=_.u(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return e;return-1};
ma=function(a,b){var c;a:if(_.u(a))c=_.u(b)&&1==b.length?a.indexOf(b,0):-1;else{for(c=0;c<a.length;c++)if(c in a&&a[c]===b)break a;c=-1}var d;(d=0<=c)&&Array.prototype.splice.call(a,c,1);return d};na=function(a){return Array.prototype.concat.apply(Array.prototype,arguments)};C=function(a){return-1!=B.indexOf(a)};oa=function(a,b){for(var c in a)b.call(void 0,a[c],c,a)};pa=function(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1};_.qa=function(a){var b=0,c;for(c in a)b++;return b};
ra=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};sa=function(){var a=r.document;return a?a.documentMode:void 0};
D=function(a){var b;if(!(b=ta[a])){b=0;for(var c=String(ua).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"",l=RegExp("(\\d*)(\\D*)","g"),k=RegExp("(\\d*)(\\D*)","g");do{var m=l.exec(g)||["","",""],p=k.exec(h)||["","",""];if(0==m[0].length&&0==p[0].length)break;b=ja(0==m[1].length?0:(0,window.parseInt)(m[1],10),0==p[1].length?0:(0,window.parseInt)(p[1],10))||ja(0==
m[2].length,0==p[2].length)||ja(m[2],p[2])}while(0==b)}b=ta[a]=0<=b}return b};
_.xa=function(a){for(var b=[],c=0,d=0;d<a.length;d++){for(var e=a.charCodeAt(d);255<e;)b[c++]=e&255,e>>=8;b[c++]=e}if(!va)for(va={},wa={},a=0;65>a;a++)va[a]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(a),wa[a]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789._-".charAt(a);a=wa;c=[];for(d=0;d<b.length;d+=3){var f=b[d],g=(e=d+1<b.length)?b[d+1]:0,h=d+2<b.length,l=h?b[d+2]:0,k=f>>2,f=(f&3)<<4|g>>4,g=(g&15)<<2|l>>6,l=l&63;h||(l=64,e||(g=64));c.push(a[k],a[f],
a[g],a[l])}return c.join("")};ya=function(){};za=function(){};Aa=function(){this.f=new window.XDomainRequest;this.readyState=0;this.responseText=this.onreadystatechange=null;this.status=-1;this.f.onload=(0,_.x)(this.pa,this);this.f.onerror=(0,_.x)(this.ka,this);this.f.onprogress=(0,_.x)(this.qa,this);this.f.ontimeout=(0,_.x)(this.ra,this)};Ba=function(a,b){a.readyState=b;if(a.onreadystatechange)a.onreadystatechange()};
_.Ca=function(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);};_.Da=function(a){return eval("("+a+")")};_.E=function(a){var b=[];Ea(new Fa,a,b);return b.join("")};Fa=function(){};
Ea=function(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if(_.da(b)){var d=b;b=d.length;c.push("[");for(var e="",f=0;f<b;f++)c.push(e),Ea(a,d[f],c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");e="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(f=b[d],"function"!=typeof f&&(c.push(e),Ga(d,c),c.push(":"),Ea(a,f,c),e=","));c.push("}");return}}switch(typeof b){case "string":Ga(b,c);break;case "number":c.push((0,window.isFinite)(b)&&
!(0,window.isNaN)(b)?String(b):"null");break;case "boolean":c.push(String(b));break;case "function":c.push("null");break;default:throw Error("Unknown type: "+typeof b);}}};Ga=function(a,b){b.push('"',a.replace(Ha,function(a){var b=Ia[a];b||(b="\\u"+(a.charCodeAt(0)|65536).toString(16).substr(1),Ia[a]=b);return b}),'"')};Ja=function(a,b){this.type=a;this.f=this.g=b};Ka=function(a){Ka[" "](a);return a};
Ma=function(a,b){Ja.call(this,a?a.type:"");this.f=this.g=null;this.screenY=this.screenX=0;this.ba=this.state=null;if(a){this.type=a.type;var c=a.changedTouches?a.changedTouches[0]:null;this.g=a.target||a.srcElement;this.f=b;var d=a.relatedTarget;if(d&&La)try{Ka(d.nodeName)}catch(e){}null===c?(this.screenX=a.screenX||0,this.screenY=a.screenY||0):(this.screenX=c.screenX||0,this.screenY=c.screenY||0);this.state=a.state;this.ba=a;a.defaultPrevented&&this.h()}};
Oa=function(a,b,c,d,e){this.listener=a;this.f=null;this.src=b;this.type=c;this.Z=!!d;this.g=e;++Na;this.Y=this.ga=!1};Pa=function(a){a.Y=!0;a.listener=null;a.f=null;a.src=null;a.g=null};Qa=function(a){this.src=a;this.f={};this.g=0};Ra=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.Y&&f.listener==b&&f.Z==!!c&&f.g==d)return e}return-1};
_.F=function(a,b,c,d,e){if(_.da(b))for(var f=0;f<b.length;f++)_.F(a,b[f],c,d,e);else if(c=Sa(c),a&&a[Ta])a.f(b,c,d,e);else{f=c;if(!b)throw Error("Invalid event type");c=!!d;var g=Ua(a);g||(a[Va]=g=new Qa(a));var h=g,l=b.toString(),g=h.f[l];g||(g=h.f[l]=[],h.g++);var k=Ra(g,f,d,e);-1<k?(d=g[k],d.ga=!1):(d=new Oa(f,h.src,l,!!d,e),d.ga=!1,g.push(d));if(!d.f){e=Wa();d.f=e;e.src=a;e.listener=d;if(a.addEventListener)a.addEventListener(b.toString(),e,c);else if(a.attachEvent)a.attachEvent(Xa(b.toString()),
e);else throw Error("addEventListener and attachEvent are unavailable.");Ya++}}};Wa=function(){var a=Za,b=$a?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b};ab=function(a,b,c,d,e){if(_.da(b))for(var f=0;f<b.length;f++)ab(a,b[f],c,d,e);else(c=Sa(c),a&&a[Ta])?a.g(b,c,d,e):a&&(a=Ua(a))&&(b=a.f[b.toString()],a=-1,b&&(a=Ra(b,c,!!d,e)),(c=-1<a?b[a]:null)&&bb(c))};
bb=function(a){if(!_.v(a)&&a&&!a.Y){var b=a.src;if(b&&b[Ta])b.h(a);else{var c=a.type,d=a.f;b.removeEventListener?b.removeEventListener(c,d,a.Z):b.detachEvent&&b.detachEvent(Xa(c),d);Ya--;(c=Ua(b))?(d=a.type,d in c.f&&ma(c.f[d],a)&&(Pa(a),0==c.f[d].length&&(delete c.f[d],c.g--)),0==c.g&&(c.src=null,b[Va]=null)):Pa(a)}}};Xa=function(a){return a in cb?cb[a]:cb[a]="on"+a};
eb=function(a,b,c,d){var e=!0;if(a=Ua(a))if(b=a.f[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.Z==c&&!f.Y&&(f=db(f,d),e=e&&!1!==f)}return e};db=function(a,b){var c=a.listener,d=a.g||a.src;a.ga&&bb(a);return c.call(d,b)};
Za=function(a,b){if(a.Y)return!0;if(!$a){var c=b||ba("window.event"),d=new Ma(c,this),e=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var f=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(l){f=!0}if(f||void 0==c.returnValue)c.returnValue=!0}c=[];for(f=d.f;f;f=f.parentNode)c.push(f);for(var f=a.type,g=c.length-1;0<=g;g--){d.f=c[g];var h=eb(c[g],f,!0,d),e=e&&h}for(g=0;g<c.length;g++)d.f=c[g],h=eb(c[g],f,!1,d),e=e&&h}return e}return db(a,new Ma(b,this))};
Ua=function(a){a=a[Va];return a instanceof Qa?a:null};Sa=function(a){if(w(a))return a;a[fb]||(a[fb]=function(b){return a.handleEvent(b)});return a[fb]};_.gb=function(a){return Math.floor(Math.random()*a)};_.G=function(a){var b,c=[];for(b=0;b<a;b+=1)c.push("abcdefghijklmnopqrstuvwxyz".charAt(_.gb(26)));return c.join("")};
_.hb=function(a,b){return new _.H(function(c,d){var e=(new za).f();e.open("GET",a,!0);e.onreadystatechange=function(){4==this.readyState&&(200==this.status&&b.apply(this,[c,d]),d(this))};e.send()})};_.ib=function(a,b){var c=(new za).f();b?(c.open("POST",a,!0),c.send(b)):(c.open("GET",a,!0),c.send())};
mb=function(a){var b=["i2",_.G(30)].join("-")+".init.cedexis-radar.net",c=["?imagesok=1","&n=",jb?1:0,"&p=",kb?1:0,"&r=",_.I?1:0,"&t=",lb?1:0];a.v&&c.push("&"+a.v);c=c.join("");return["/",b,"i2",a.g,a.f,"j1/20/22",Math.floor(_.z()/1E3).toString(10),"providers.json"].join("/")+c};nb=function(a){a=mb(a);return _.hb(a,function(a,c){try{var d=_.Da(this.responseText);a(d)}catch(e){c(e)}})};
pb=function(a,b){var c=(window.performance||{}).timing;if(c&&ob(a))if(0===c.loadEventEnd)b=b||0,20>b&&window.setTimeout(_.y(pb,a,b+1),200);else if(!(c.connectEnd<c.connectStart||c.domainLookupEnd<c.domainLookupStart||c.domComplete<c.domLoading||c.fetchStart<c.navigationStart||c.loadEventEnd<c.loadEventStart||c.loadEventEnd<c.navigationStart||c.responseEnd<c.responseStart||c.responseStart<c.requestStart)){var d=[a.v,"n1",0];_.A(qb,function(a){d.push(c[a]||0)});d.push(a.g);d.push(rb(a.f));d.push(sb());
_.ib("//"+d.join("/"))}};sb=function(){var a=0;window.chrome&&window.chrome.loadTimes?(a=window.chrome.loadTimes(),a=Math.round(1E3*a.firstPaintTime)):window.performance&&window.performance.timing&&window.performance.timing.msFirstPaint&&(a=Math.round(window.performance.timing.msFirstPaint));return a};tb=function(a,b,c,d){this.h=a;this.w=b;this.o=c;this.v=d;this.f=void 0;this.j=[];this.l=[]};
vb=function(a,b,c,d){0==c||_.q(a.f)||(a.f=2,ub(a));-1==b?0==c&&(a.f=d,ub(a)):a.l[b]||(a.l[b]=!0,0==b&&vb(a,1,c,d),a.j.push([b,c,d]),ub(a))};ub=function(a){if(_.q(a.f))for(;a.j.length;)a.A.apply(a,a.j.shift())};wb=function(a,b){this.h=a;this.j=b;this.g=0;this.f=null};xb=function(a){var b;0<a.g?(a.g--,b=a.f,a.f=b.next,b.next=null):b=a.h();return b};yb=function(a,b){a.j(b);100>a.g&&(a.g++,b.next=a.f,a.f=b)};Ab=function(){var a=zb,b=null;a.f&&(b=a.f,a.f=a.f.next,a.f||(a.g=null),b.next=null);return b};
Bb=function(){this.next=this.g=this.f=null};Cb=function(a){r.setTimeout(function(){throw a;},0)};
Db=function(){var a=r.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!C("Presto")&&(a=function(){var a=window.document.createElement("IFRAME");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,_.x)(function(a){if(("*"==d||a.origin==
d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!C("Trident")&&!C("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(_.q(c.next)){c=c.next;var a=c.ia;c.ia=null;a()}};return function(a){d.next={ia:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("SCRIPT")?function(a){var b=window.document.createElement("SCRIPT");
b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){r.setTimeout(a,0)}};_.Ib=function(a,b){Eb||Fb();Gb||(Eb(),Gb=!0);var c=zb,d=xb(Hb);d.f=a;d.g=b;d.next=null;c.g?c.g.next=d:c.f=d;c.g=d};
Fb=function(){if(r.Promise&&r.Promise.resolve){var a=r.Promise.resolve(void 0);Eb=function(){a.then(Jb)}}else Eb=function(){var a=Jb;!w(r.setImmediate)||r.Window&&r.Window.prototype&&!C("Edge")&&r.Window.prototype.setImmediate==r.setImmediate?(Kb||(Kb=Db()),Kb(a)):r.setImmediate(a)}};Jb=function(){for(var a=null;a=Ab();){try{a.f.call(a.g)}catch(b){Cb(b)}yb(Hb,a)}Gb=!1};
_.H=function(a,b){this.g=Lb;this.w=void 0;this.j=this.h=this.l=null;this.o=this.v=!1;if(a!=t)try{var c=this;a.call(b,function(a){c.f(Mb,a)},function(a){c.f(J,a)})}catch(d){this.f(J,d)}};Nb=function(){this.next=this.h=this.g=this.j=this.f=null;this.l=!1};Pb=function(a,b,c){var d=xb(Ob);d.j=a;d.g=b;d.h=c;return d};_.Qb=function(){var a=new _.H(t);a.f(Mb,void 0);return a};Sb=function(a,b){a.h||a.g!=Mb&&a.g!=J||Rb(a);a.j?a.j.next=b:a.h=b;a.j=b};
Tb=function(a,b,c,d){var e=Pb(null,null,null);e.f=new _.H(function(a,g){e.j=b?function(c){try{var e=b.call(d,c);a(e)}catch(k){g(k)}}:a;e.g=c?function(b){try{var e=c.call(d,b);a(e)}catch(k){g(k)}}:g});e.f.l=a;Sb(a,e);return e.f};_.Vb=function(a,b,c,d){if(a instanceof _.H)return Sb(a,Pb(b||t,c||null,d)),!0;var e;if(a)try{e=!!a.$goog_Thenable}catch(g){e=!1}else e=!1;if(e)return a.then(b,c,d),!0;if(_.ea(a))try{var f=a.then;if(w(f))return Ub(a,f,b,c,d),!0}catch(g){return c.call(d,g),!0}return!1};
Ub=function(a,b,c,d,e){function f(a){h||(h=!0,d.call(e,a))}function g(a){h||(h=!0,c.call(e,a))}var h=!1;try{b.call(a,g,f)}catch(l){f(l)}};Rb=function(a){a.v||(a.v=!0,_.Ib(a.A,a))};Wb=function(a){var b=null;a.h&&(b=a.h,a.h=b.next,b.next=null);a.h||(a.j=null);return b};Xb=function(a,b,c){b==Mb?a.j.call(a.h,c):a.g&&a.g.call(a.h,c)};Zb=function(a,b){a.o=!0;_.Ib(function(){a.o&&Yb.call(null,b)})};
L=function(a){ha("radar.stoppedAt",null);ha("cedexis.radar.stopped_at",null);var b=window.document.createElement("script");b.type="text/javascript";b.async=!0;b.src=K(a);b.onerror=a.reject;void 0!==b.onreadystatechange?b.onreadystatechange=_.y(L.g,a):b.onload=_.y(L.f,a);window.document.body.appendChild(b);$b(a,function(){window.document.body.removeChild(b)})};
ac=function(){var a=window.performance.getEntries().length;if(1500<=a)window.performance.clearResourceTimings();else{for(var b=0;1500>b&&b<=a;)b+=50;150>=b&&(b=150);window.performance.setResourceTimingBufferSize(b)}};
cc=function(a,b,c,d,e){var f;a:{if(_.I){f=window.performance.getEntriesByType("resource");for(var g=f.length;g--;)if(f[g].name===this.src){f=f[g];break a}}bc=!0;f=null}if(_.ea(f)){if(0==f.duration&&(_.v(e)||(e=0),10>e)){window.setTimeout((0,_.x)(cc,this,a,b,c,d,e+1),10);return}f[b]&&f[c]&&f[c]>=f[b]?M(d,a(f[c]-f[b])):M(d,a(f.duration))}else 1===d.M?M(d,_.z()-d.W()):M(d)};
ec=function(a){if(14===a.M){var b="responseEnd",c=dc(a)||1E5;cc.apply(this,[function(a){return 8*c/a},"requestStart",b,a])}else cc.apply(this,[function(a){return a},"requestStart","responseStart",a])};fc=function(a){cc.apply(this,[function(a){return a},"domainLookupStart","domainLookupEnd",a])};
hc=function(a,b,c){if(kb){var d=gc();d.src=K(a);var e=function(a){a=a.ba;a.source==d.contentWindow&&b(a.data)};_.F(window,"message",e);c&&_.F(d,"load",c);window.document.body.appendChild(d);$b(a,function(){window.document.body.removeChild(d);ab(window,"message",e)})}else a.reject()};
jc=function(a){var b=a.$,c=0,b=b.slice(b.lastIndexOf("/")+1),d=[/cdx10b/,/rdr12/,/radar\.js/,/r\d+(-\d+kb)?\.js/i,/r\d+\w+(-\d+kb)?\.js/i],e;"d17.html"===b&&(c=c||4);for(e=0;e<d.length;e+=1)d[e].test(b)&&(c=c||1);/\.js(\?)?/i.test(b)&&(c=c||5);/\.(ico|png|bmp|gif|jpg|jpeg)(\?)?/i.test(b)&&(c=c||2);/\.(htm(l)?)(\?)?/i.test(b)&&(c=c||3);return c?ic(c,a):a.reject};
kc=function(a){ha("cdx.s.b",_.y(kc.listener,a));var b=window.document.createElement("script");b.type="text/javascript";b.async=!0;b.src=K(a);window.document.body.appendChild(b);$b(a,function(){window.document.body.removeChild(b)})};
lc=function(a){try{var b=la(a.providers,function(a){return 32098==a.p.i});0<=b&&(b+=_.gb(2),a.providers.splice(b,0,{p:{p:{a:{c:{u:"http://ipv6test.lhr.hv.bench.cedexis-test.com/img/inav-100KB.html",t:20},b:{u:"http://ipv6test.lhr.hv.bench.cedexis-test.com/img/inav.html",t:20},a:{u:"http://ipv6test.lhr.hv.bench.cedexis-test.com/img/inav.html",t:20}}},i:31789,c:0,z:0},a:!0}))}catch(c){}return a};ic=function(a,b){var c=N[a];c==jc&&(c=c(b));return c?c:function(a){a.reject()}};
O=function(a,b,c){this.L=a;this.M=b;this.o=c.t;this.$=c.u;this.w=c.timeout||a.f.timeout||4E3;this.f=[];this.reject=(0,_.x)(this.reject,this)};K=function(a){var b=a.$;if(!a.L.f.a)return b;var c=[a.L.h.f.g,a.L.h.f.f,a.L.f.p.z,a.L.f.p.c,a.L.g()],c=-1==a.M?na(c,_.G(8)):na(a.M,c,a.L.h.D),c=na(c,a.L.h.g).join("-");return b+(-1!=b.indexOf("?")?"&":"?")+"rnd="+c};dc=function(a){if(a.j)return a.j;if((a=/(\d+)kb\./i.exec(a.$))&&a[1])return Math.floor(1E3*(0,window.parseInt)(a[1],10)+2E-15)};
gc=function(){var a=window.document.createElement("iframe");a.style.display="none";a.title="Cedexis Test Object";a.setAttribute("aria-hidden","true");return a};mc=function(a){return _.q(a.h)?(window.clearTimeout(a.h),delete a.h,!1):!0};M=function(a,b){if(!mc(a))for(_.v(b)&&(b=Math.floor(b+2E-15)),_.q(b)&&vb(a.V(),a.M,0,b),a.l(b);a.f.length;)a.f.shift()()};$b=function(a,b){a.f.push(b)};
nc=function(a,b){this.h=a;this.f=b;var c=ba("c.a",b),d=ba("c.b",b),e=ba("c.c",b);null===c&&(c=this.f.p.z);null===d&&(d=this.f.p.c);null===e&&(e=this.g());this.j=new tb(a,c,d,e);null===ba("p.p.d",b)&&(c=this.j,c.f=0,ub(c))};
oc=function(a){var b=[],c=a.f.p.p;c.a&&c.a.a?b.push(new O(a,1,c.a.a)):c.b&&c.b.a&&b.push(new O(a,1,c.b.a));c.d&&b.push(new O(a,-1,c.d));c.a?(c.a.b&&b.push(new O(a,0,c.a.b)),c.a.c&&b.push(new O(a,14,c.a.c))):c.b&&(c.b.b&&b.push(new O(a,0,c.b.b)),c.b.c&&b.push(new O(a,14,c.b.c)));if(c.c){var d;d=c.c.u;(d=/http:/i.test(d)?"http":/https:/i.test(d)?"https":/\/\//.test(d)?window.location.protocol.replace(":",""):null)&&("http:"!==window.location.protocol&&"https"!==d||b.push(new O(a,2,c.c)))}return b};
sc=function(a,b,c,d){_.q(d)||(d=-1);_.q(c)||(c=a);this.g=a;this.J=d;this.O=null;"radar"in pc||(pc.radar=new qc);var e=pc.radar,f=this;(new _.H(function(a){f.f=a})).then(function(){return b(c).then((0,_.x)(e.o,e,f),function(){e.o(f)})});rc(e,this)};qc=function(){this.g={};this.j={};this.f=null;this.l=[];this.h=null};tc=function(a,b){var c=a;if(!a||b.J<c.J)b.O=c,a=b;else for(;;){if(!c.O||b.J<c.O.J){b.O=c.O;c.O=b;break}c=c.O}return a};rc=function(a,b){var c=b.g.da;a.g[c]=tc(a.g[c],b);a.next()};
uc=function(a){var b=a.f;a.f=a.f.O;a.l.push(b);b.f()};
xc=function(a,b){this.f=a;this.g=b.sig;this.D=b.txnId;var c=b.providers,d=b.radar;this.v=d.report_domain||"rpt.cedexis.com";this.C=0==d.navigation_timing_enabled==0;this.o=d.startup_delay;_.v(this.o)||(this.o=2E3);this.h=d.master_sample_rate;_.v(this.h)||(this.h=1);this.j=d.navigation_timing_sample_rate;_.v(this.j)||(this.j=1);this.l=d.remote_probing_sample_rate;_.v(this.l)||(this.l=1);var e=this;vc(e)&&_.A(c,function(a){a=new nc(e,a);wc(e,a.X,a)})};wc=function(a,b,c){new sc(a.f,b,c,a.o)};
yc=function(a){_.q(a.w)||(a.w=Math.random()<a.h);return a.w};vc=function(a){_.q(a.B)||(a.B=yc(a)&&Math.random()<a.l);return a.B};ob=function(a){_.q(a.A)||(a.A=yc(a)&&a.C&&Math.random()<a.j);return a.A};Bc=function(a){return function(b){var c=zc[a]||Ac(a);zc[a]=c.then(b).then(t)}};Cc=function(){};Ac=function(a){var b=Dc[a],c=b.length,d=new _.H(function(a){_.A(b,function(b){Bc(b)(function(){--c;c||a()})})});_.A(Ec[a],function(a){d=d.then(_.y(Fc,a))});return d};
Fc=function(a){return new _.H(function(b){var c=window.document.createElement("script");c.async=!0;c.type="text/javascript";c.src=Gc+a;c.onload=c.onreadystatechange=function(){c.readyState&&"loaded"!=c.readyState&&"complete"!=c.readyState||(window.document.body.removeChild(c),b())};window.document.body.appendChild(c)})};P=function(a,b){this.g=a;this.f=b;this.da=a+";"+b;var c=Hc[this.da];if(c)return c;Hc[this.da]=this};Jc=function(a,b){Ic(a,function(a){a.la(b)})};
Ic=function(a,b){a.o||(a.o=new _.H((0,_.x)(function(a){this.h=(0,_.x)(function(b){b=new _.Q(window,window.document,this,b);b.G();a(b)},this)},a)));a.F?a.j||Kc(a,{}):a.start();a.o=a.o.then(function(a){b(a);return a})};Kc=function(a,b){if(a.h){var c=a.h;a.h=!1;var d=(0,_.x)(function(){var a=new _.Q(window,window.document,this,b);a.G();c(a)},a);Lc(d)}};
rb=function(a){if(a=a.C){var b;try{b=_.E(a),b=_.xa(b)}catch(d){return"error"}return"impact_kpi:"+b}b=[];for(var c in window){a=null;if(void 0!==window.hasOwnProperty)window.hasOwnProperty(c)&&(a=Mc(c));else try{void 0!==window[c]&&(a=Mc(c))}catch(d){}a&&b.push(a)}return 1>b.length?"0":b.join("@")};
Mc=function(a){var b=/radar_(tags|impact)_(\w{3,})/i,c;if(("radar_tags_"===a.slice(0,11)||"radar_impact_"===a.slice(0,13))&&(b=b.exec(a))&&3===b.length){try{c=_.E(window[a])}catch(d){return null}return b[2]+":"+_.xa(c)}return null};
Nc=function(a,b,c,d){if(Nc.f()){_.v(a)&&_.v(b)&&(new P(a,b)).start(c,d);var e=/\/(\d)\/(\d+)\/radar\.js/,f=/\/([\d]{1,2})-(\d{1,5})-radar10\.min\.js/;_.A(window.document.getElementsByTagName("script"),function(a){var b=e.exec(a.src)||f.exec(a.src);b&&b[2]&&(a=(0,window.parseInt)(b[1],10),b=(0,window.parseInt)(b[2],10),(a||b)&&(new P(a,b)).start())})}};r=this;var Oc=_,Dc=Oc.MI,Ec=Oc.MU,Gc=Oc.MP,Pc=Oc.custom;var B;a:{var Qc=r.navigator;if(Qc){var Rc=Qc.userAgent;if(Rc){B=Rc;break a}}B=""};var Sc=C("Opera"),R=C("Trident")||C("MSIE"),Tc=C("Edge"),La=C("Gecko")&&!(-1!=B.toLowerCase().indexOf("webkit")&&!C("Edge"))&&!(C("Trident")||C("MSIE"))&&!C("Edge"),Uc=-1!=B.toLowerCase().indexOf("webkit")&&!C("Edge"),Vc=Uc&&C("Mobile"),ua;
a:{var Wc="",Xc=function(){var a=B;if(La)return/rv\:([^\);]+)(\)|;)/.exec(a);if(Tc)return/Edge\/([\d\.]+)/.exec(a);if(R)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Uc)return/WebKit\/(\S+)/.exec(a);if(Sc)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Xc&&(Wc=Xc?Xc[1]:"");if(R){var Yc=sa();if(null!=Yc&&Yc>(0,window.parseFloat)(Wc)){ua=String(Yc);break a}}ua=Wc}var ta={},Zc=r.document,$c=Zc&&R?sa()||("CSS1Compat"==Zc.compatMode?(0,window.parseInt)(ua,10):5):void 0;var va=null,wa=null;ia(za,ya);za.prototype.f=function(){var a=new window.XMLHttpRequest;if("withCredentials"in a)return a;if("undefined"!=typeof window.XDomainRequest)return new Aa;throw Error("Unsupported browser");};_.n=Aa.prototype;_.n.open=function(a,b,c){if(null!=c&&!c)throw Error("Only async requests are supported.");this.f.open(a,b)};_.n.send=function(a){if(a)if("string"==typeof a)this.f.send(a);else throw Error("Only string data is supported");else this.f.send()};
_.n.pa=function(){this.status=200;this.responseText=this.f.responseText;Ba(this,4)};_.n.ka=function(){this.status=500;this.responseText=null;Ba(this,4)};_.n.ra=function(){this.ka()};_.n.qa=function(){this.status=200;Ba(this,1)};_.n.getAllResponseHeaders=function(){return"content-type: "+this.f.contentType};var Ia={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},Ha=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;var ad;(ad=!R)||(ad=9<=Number($c));var $a=ad,bd=R&&!D("9");!Uc||D("528");La&&D("1.9b")||R&&D("8")||Sc&&D("9.5")||Uc&&D("528");La&&!D("8")||R&&D("9");Ja.prototype.h=function(){};Ka[" "]=t;ia(Ma,Ja);Ma.prototype.h=function(){Ma.Ca.h.call(this);var a=this.ba;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,bd)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var Ta="closure_listenable_"+(1E6*Math.random()|0),Na=0;Qa.prototype.hasListener=function(a,b){var c=_.q(a),d=c?a.toString():"",e=_.q(b);return pa(this.f,function(a){for(var g=0;g<a.length;++g)if(!(c&&a[g].type!=d||e&&a[g].Z!=b))return!0;return!1})};var Va="closure_lm_"+(1E6*Math.random()|0),cb={},Ya=0,fb="__closure_events_fn_"+(1E9*Math.random()>>>0);var kb,jb,lb;kb=function(){if(!w(window.postMessage))return!1;try{return _.F(window,"message",t),ab(window,"message",t),!0}catch(a){return!1}}();jb=5==$c?!1:window.performance&&_.ea(window.performance.timing)?!0:!1;_.I=R&&!D(11)?!1:window.performance&&w(window.performance.getEntriesByType)&&w(window.performance.getEntries)&&w(window.performance.clearResourceTimings)&&w(window.performance.setResourceTimingBufferSize)?!0:!1;lb=!Vc;var cd;try{(new za).f(),cd=!0}catch(a){cd=!1};var qb="navigationStart unloadEventStart unloadEventEnd redirectStart redirectEnd fetchStart domainLookupStart domainLookupEnd connectStart connectEnd secureConnectionStart requestStart responseStart responseEnd domLoading domInteractive domContentLoadedEventStart domContentLoadedEventEnd domComplete loadEventStart loadEventEnd".split(" ");tb.prototype.A=function(a,b,c){a=["/",this.h.v,"f1",this.h.g,this.w,this.o,this.v,a,b,c,this.f,rb(this.h.f)];this.g&&(a=a.concat(this.g));_.ib(a.join("/"))};var Hb=new wb(function(){return new Bb},function(a){a.reset()});Bb.prototype.reset=function(){this.next=this.g=this.f=null};var Kb;var Eb,Gb=!1,zb=new function(){this.g=this.f=null};var Lb=0,Mb=2,J=3;Nb.prototype.reset=function(){this.h=this.g=this.j=this.f=null;this.l=!1};var Ob=new wb(function(){return new Nb},function(a){a.reset()});_.H.prototype.then=function(a,b,c){return Tb(this,w(a)?a:null,w(b)?b:null,c)};var dd=_.H;dd.prototype.then=dd.prototype.then;dd.prototype.$goog_Thenable=!0;_.H.prototype.B=function(a){this.g=Lb;this.f(Mb,a)};_.H.prototype.C=function(a){this.g=Lb;this.f(J,a)};
_.H.prototype.f=function(a,b){this.g==Lb&&(this==b&&(a=J,b=new TypeError("Promise cannot resolve to itself")),this.g=1,_.Vb(b,this.B,this.C,this)||(this.w=b,this.g=a,this.l=null,Rb(this),a!=J||Zb(this,b)))};_.H.prototype.A=function(){for(var a=null;a=Wb(this);){var b=this.g,c=this.w;if(b==J&&a.g&&!a.l)for(var d=void 0,d=this;d&&d.o;d=d.l)d.o=!1;if(a.f)a.f.l=null,Xb(a,b,c);else try{a.l?a.j.call(a.h):Xb(a,b,c)}catch(e){Yb.call(null,e)}yb(Ob,a)}this.v=!1};var Yb=Cb;L.g=function(a){"loaded"!==this.readyState&&"complete"!==this.readyState||L.f(a)};L.f=function(a){var b=(window.radar.stoppedAt||window.cedexis.radar.stopped_at||new Date).getTime()-a.W();14===a.M&&(b=8*(dc(a)||1E5)/b);M(a,b)};_.I&&(ac(),w(window.performance.addEventListener)?_.F(window.performance,"resourcetimingbufferfull",ac):window.performance.onresourcetimingbufferfull||(window.performance.onresourcetimingbufferfull=ac));var bc=!1;kc.listener=function(a,b){_.ea(b)&&b.id==a.L.g()&&M(a,b.node)};var N={};N[1]=L;N[2]=function(a){if(1===a.M||!bc&&_.I){var b=new window.Image;b.onload=_.y(ec,a);b.onerror=a.reject;b.src=K(a)}else M(a)};N[3]=function(a){var b=gc();b.src=K(a);b.onload=function(){M(a,_.z()-a.W())};b.onerror=a.reject;window.document.body.appendChild(b);$b(a,function(){window.document.body.removeChild(b)})};
N[4]=function(a){hc(a,function(b){b=_.Ca(b);switch(b.s){case "l":break;case "s":var c=a.V(),d=b.m.ciphertext;c.g=c.g||[];c.g.push(d);M(a,b.m.responseEnd-b.m.domainLookupStart);break;default:a.reject()}})};N[5]=L;N[6]=jc;N[7]=function(a){kb?hc(a,function(b){b=_.Ca(b);switch(b.s){case "l":break;case "e":a.reject();break;case "s":var c=b.node_id;!1===b.encoded&&(c=(0,window.encodeURIComponent)("base64:"+_.xa(c)));M(a,c);break;default:a.reject()}}):M(a,1)};N[8]=kc;
N[9]=function(a){if(!bc&&_.I){var b=new window.Image,c=a.$,d=c.indexOf("//"),e=c.substring(d+2),f="//";0<d&&(f=c.substring(0,d)+"//");c=e.split("/");c[0]=_.G(63)+"."+c[0];b.src=f+c.join("/");b.onload=_.y(fc,a);b.onerror=a.reject}else a.reject()};N[11]=function(a){if(1===a.M||!bc&&_.I){var b=gc();b.onload=_.y(ec,a);b.src=K(a);window.document.body.appendChild(b);$b(a,function(){window.document.body.removeChild(b)})}else M(a)};
N[20]=function(a){hc(a,function(b){if(14===a.M&&b[2]&&b[2]>b[0]){var c=dc(a)||1E5;M(a,8*c/(b[2]-b[0]))}else b[1]&&b[1]>b[0]?M(a,b[1]-b[0]):a.reject()},function(a){a.f.contentWindow.postMessage([["timing","requestStart"],["timing","responseStart"],["timing","responseEnd"],["cedexis","ZoneID"],["cedexis","ProviderID"],["cedexis","UniqueID"],["cedexis","FileSize"]],"*")})};O.prototype.V=function(){return this.L.V()};O.prototype.W=function(){return this.g};O.prototype.X=function(){this.g=_.z();var a=this;this.h=window.setTimeout(function(){a.reject(1)},this.w);var b=ic(this.o,this);return new _.H(function(c,d){a.l=c;a.v=d;b.apply(a,[a])})};O.prototype.reject=function(a){if(!mc(this))for(_.v(a)||(a=4),vb(this.V(),this.M,a,0),this.v(a);this.f.length;)this.f.shift()()};nc.prototype.V=function(){return this.j};nc.prototype.g=function(){return this.f.p.i};nc.prototype.X=function(a){a=oc(a||this);var b=_.Qb();_.A(a,function(a){b=b.then((0,_.x)(a.X,a))});return b};var fd=_.z();if("complete"!=window.document.readyState){var gd=function(){fd=_.z();oa(pc,function(a){a.next()});ab(window,"load",gd)},fd=fd+6E4;_.F(window,"load",gd)}var pc={};
qc.prototype.next=function(){(0,window.clearTimeout)(this.h);this.h=null;this.f||(this.j={});var a=_.z()-fd;for(_.A(ra(this.g),function(b){for(var d=this.g[b];d&&d.J<=a;){var e=0;if(0>d.J)e=-1;else{var f=this.f?this.f.J:0,g=this.j[b];g&&(f>g?e=f:e=g);this.j[b]=e+1}f=d.O;d.J=e;this.f=tc(this.f,d);d=f}d?this.g[b]=d:delete this.g[b]},this);this.f&&0>this.f.J;)uc(this);if(!this.l.length)if(this.f)uc(this);else if(0!=_.qa(this.g)){var b=null;oa(this.g,function(a){if(!b||b>a.J)b=a.J});b&&(this.h=window.setTimeout((0,_.x)(this.next,
this),fd+b-_.z()))}};qc.prototype.o=function(a){ma(this.l,a);this.next()};var zc={radar:_.Qb()};ha("cedexis.impact",function(a,b,c){Jc(new P(a,b),c)});var Lc;_.Q=Cc;Lc=Bc("impact");var hd;_.S=Cc;hd=Bc("video");var Hc={};P.prototype.start=function(a,b){this.B||(this.B=this.j=this.F=!0,this.A=a||1,this.v=b,nb(this).then((0,_.x)(this.w,this),(0,_.x)(this.l,this)))};P.prototype.l=function(){this.j=!1;--this.A;this.A?nb(this).then((0,_.x)(this.w,this),(0,_.x)(this.l,this)):(0,window.setTimeout)((0,_.x)(function(){this.B=!1},this),6E4)};
P.prototype.w=function(a){a=lc(a);w(Pc)&&(a=Pc(this.g,this.f,a));var b=(0,_.x)(this.l,this),c=new xc(this,a);wc(c,function(){return new _.H(function(a){b();a()})});if(this.j){var d=a.impactKpis4;!d&&this.h&&(d={});d?(Ic(this,function(){pb(c)}),Kc(this,d)):pb(c);(a=a.videoQoS)&&hd((0,_.x)(this.D,this,a));this.j=!1}};P.prototype.D=function(a){(new _.S(this.g,this.f,a)).na()};ha("cedexis.start",Nc);Nc.f=function(){var a=B;return ka(function(b){return-1!=a.toLowerCase().indexOf(b.toLowerCase())?!0:!1})?!1:cd};
})(cedexis)}cedexis.start();

